### ISSUE TITLE
Python3 write_channel "Can't convert 'bytes' object to str implicitly"

### ISSUE THREAD

**Issue by hdimitriou** [kubernetes-client/python-base#151]
I am using the rundeck kubernetes plugin to execute a script to a pod and I get the following error
```
15:53:46 | Traceback (most recent call last):
-- | --
15:53:46 | File "/home/rundeck/libext/cache/kubernetes-plugin-1.10.1-SNAPSHOT/pods-copy-file.py", line 69, in <module>
15:53:46 | main()
15:53:46 | File "/home/rundeck/libext/cache/kubernetes-plugin-1.10.1-SNAPSHOT/pods-copy-file.py", line 65, in main
15:53:46 | common.copy_file(name, namespace, container, source_file, destination_path, destination_file_name)
15:53:46 | File "/home/rundeck/libext/cache/kubernetes-plugin-1.10.1-SNAPSHOT/common.py", line 396, in copy_file
15:53:46 | resp.write_stdin(c)
15:53:46 | File "/usr/local/lib/python3.5/dist-packages/kubernetes/stream/ws_client.py", line 160, in write_stdin
15:53:46 | self.write_channel(STDIN_CHANNEL, data)
15:53:46 | File "/usr/local/lib/python3.5/dist-packages/kubernetes/stream/ws_client.py", line 114, in write_channel
15:53:46 | self.sock.send(chr(channel) + data)
15:53:46 | TypeError: Can't convert 'bytes' object to str implicitly
```

On this [comment](https://github.com/kubernetes-client/python/issues/476#issuecomment-375056804) there is a workaround - a change to [ws_client.py](https://github.com/kubernetes-client/python-base/blob/master/stream/ws_client.py)
```
def write_channel(self, channel, data):
    """Write data to a channel."""
    self.sock.send(bytes(chr(channel), 'utf-8') + data)
```

This worked for me, so maybe someone with more knowledge can see if it should be merged fixed this way, or there's something better

I am using 'Python 3.5.2' and I tried kubernetes 9.0.0 and 10.0.0
This issue does not happen with Python2.7

**Comment by roycaihw** [comment]
The ws client we use `OPCODE_TEXT` by default, which accepts utf-8 string or unicode as payload https://github.com/websocket-client/websocket-client/blob/66081be8e0523c9dfaffcb18ba1c8e4765e2288e/websocket/_core.py#L241-L253.

I think the error means that we don't support bytes payload yet. One fix could be supporting the `opcode` parameter in our client and do the `bytes(chr(channel), 'utf-8')` conversion when necessary, but we need to test that

I will work on this when I get time, but in the meantime feel free to jump in if anyone is interested.

/help

**Comment by sergei-maertens** [comment]
I'll give this a stab

**Comment by Ark-kun** [comment]
I'm not sure this issue is fixed.
/reopen

**Comment by roycaihw** [comment]
/reopen
/remove-lifecycle rotten
/unassign

This issue still exists

**Comment by roycaihw** [comment]
Fixed by #152

/close
